### ISSUE TITLE
Failed to load configured vocabulary directory.

### ISSUE THREAD

**Issue by jsarunas** [onc-healthit/ccda-scorecard#143]
Hi guys,
When scorecard starts, i get an error in scorecard logs:
"[VocabularyLoadRunner:89] Failed to load configured vocabulary directory."

It seems that application could not load files located in "WEB-INF/classes/code_repository"
This folder contains 4 folders with csv files in it and it seems that those could not be loaded.

It looks like that there is a need to configure hsql as for some reason connection to internal database could not be established. May be someone already was on this before and knows how to solve it.
Documentation doesn't provide such information.  

Thank you very much for your time.

Kind Regards
Jonas

**Comment by drbgfc** [comment]
Is this in regards to the local version https://github.com/siteadmin/ccda-scorecard-local-instantiation or are you running the version in this repo, locally?

**Comment by jsarunas** [comment]
Hi Dan,

Yes, we used local version. Folder scorecarddatabase gets created when tomcat service starts and it is created in Tomcat folder. Is it possible somehow to define where exactly this database should be created by using parameter?  Applications scorecard and referenceccdaservice are located in Tomcat/webapps. I was trying to identify problem by checking source code file located at 
ccda-scorecard-master\src\main\java\org\sitenv\service\ccda\smartscorecard\cofiguration\PersistanceConfiguration.java
I noticed that hsql JDBC url is hard coded in HSQL_JDBC_URL_TEMPLATE and that makes custom configuration more difficult. It would be nice to have this as a parameter controllable from config file at least location to db file jdbc:hsqldb:file should be controllable I think.
In my case I guess database connection could not be created as it points to file in wrong location.
We have now in code jdbc hsqldb file to scorecarddatabase/db and it is hard coded. In my case I believe it should be ../../scorecarddatabase/db

I managed to overcome this problem by manually importing data to scorecarddatabase/db by using 'Execute Query' app and commenting out schema.sql file located at 
Tomcat 7.0\webapps\scorecard\WEB-INF\classes\schema.sql

So that's a story.

Kind Regards
Jonas

**Comment by drbgfc** [comment]
Thanks for the info - I am going to assign this to Mounika as she handled that port / handles that repo. She should be able to help you and update the product if needed accordingly.

**Comment by monikadrajer** [comment]
Hi Jonas, 

Thanks for the info!! The idea is any one (including non technical people) should be able to run scorecard in local with minimal effort; hence hsqldb URL was not exposed as configurable property. We never had any issues in the past in regards with loading vocabulary config files from classpath. 

We are logging the exception in case of failing to load vocabulary config files. If possible could you please share the error stack trace..?

**Comment by jsarunas** [comment]
Hi Monika,

Yes, I get an idea and I am sharing logs with you.
Please find stack trace below:
01:10:52,806 INFO  [LogHelper:31] HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
01:10:52,978 INFO  [Version:37] HHH000412: Hibernate Core {5.0.7.Final}
01:10:52,978 INFO  [Environment:213] HHH000206: hibernate.properties not found
01:10:52,978 INFO  [Environment:317] HHH000021: Bytecode provider name : javassist
01:10:53,056 INFO  [Version:66] HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
01:10:53,572 INFO  [ENGINE:?] dataFileCache open start
01:10:53,588 INFO  [ENGINE:?] dataFileCache open end
01:10:53,588 INFO  [ENGINE:?] checkpointClose start
01:10:53,588 INFO  [ENGINE:?] checkpointClose synched
01:10:53,603 INFO  [ENGINE:?] checkpointClose script done
01:10:53,603 INFO  [ENGINE:?] dataFileCache commit start
01:10:53,603 INFO  [ENGINE:?] dataFileCache commit end
01:10:53,619 INFO  [ENGINE:?] checkpointClose end
01:10:53,681 INFO  [Dialect:156] HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
01:10:54,025 WARN  [SessionFactoryBuilderImpl:648] Unrecognized hbm2ddl_auto value : none.  Supported values include create, create-drop, update, and validate.  Ignoring
01:10:54,760 INFO  [QueryTranslatorFactoryInitiator:47] HHH000397: Using ASTQueryTranslatorFactory
01:10:56,463 INFO  [VocabularyLoadRunner:81] Loading vocabularies at: C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\scorecard\WEB-INF\classes\code_repository...
01:10:56,463 ERROR [VocabularyLoadRunner:89] Failed to load configured vocabulary directory.
java.lang.NullPointerException
	at org.sitenv.service.ccda.smartscorecard.loader.VocabularyLoadRunner.loadDirectory(VocabularyLoadRunner.java:23)
	at org.sitenv.service.ccda.smartscorecard.loader.VocabularyLoadRunner.afterPropertiesSet(VocabularyLoadRunner.java:82)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5155)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5680)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:712)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:2003)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Thanks for your time and your help.

P.S.  Problem could be related to our Tomcat configuration.
I am .Net developer :) and do not know to be honest how to configure hsql correctly.
I expected to run that baby right out from the box but we failed with loading those files.

Kind Regards
Jonas

**Comment by Savithanpc** [comment]
Hello monika, 

Even i am getting same error. Please find the exception for scorecard

C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin>catalina.bat run
Using CATALINA_BASE:   "C:\Program Files\Apache Software Foundation\Tomcat 9.0"
Using CATALINA_HOME:   "C:\Program Files\Apache Software Foundation\Tomcat 9.0"
Using CATALINA_TMPDIR: "C:\Program Files\Apache Software Foundation\Tomcat 9.0\temp"
Using JRE_HOME:        "C:\Program Files\Java\jre1.8.0_291"
Using CLASSPATH:       "C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin\bootstrap.jar;C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin\tomcat-juli.jar"
Using CATALINA_OPTS:   ""
27-Aug-2021 22:16:29.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.52
27-Aug-2021 22:16:29.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jul 31 2021 04:12:17 UTC
27-Aug-2021 22:16:29.611 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.52.0
27-Aug-2021 22:16:29.614 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
27-Aug-2021 22:16:29.615 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
27-Aug-2021 22:16:29.615 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
27-Aug-2021 22:16:29.615 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Program Files\Java\jre1.8.0_291
27-Aug-2021 22:16:29.616 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_291-b10
27-Aug-2021 22:16:29.616 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
27-Aug-2021 22:16:29.617 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Program Files\Apache Software Foundation\Tomcat 9.0
27-Aug-2021 22:16:29.617 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\Program Files\Apache Software Foundation\Tomcat 9.0
27-Aug-2021 22:16:29.618 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Program Files\Apache Software Foundation\Tomcat 9.0\conf\logging.properties
27-Aug-2021 22:16:29.618 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
27-Aug-2021 22:16:29.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
27-Aug-2021 22:16:29.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
27-Aug-2021 22:16:29.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
27-Aug-2021 22:16:29.619 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Program Files\Apache Software Foundation\Tomcat 9.0
27-Aug-2021 22:16:29.620 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\Program Files\Apache Software Foundation\Tomcat 9.0
27-Aug-2021 22:16:29.620 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\Program Files\Apache Software Foundation\Tomcat 9.0\temp
27-Aug-2021 22:16:29.624 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [C:\Program Files\Java\jre1.8.0_291\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Softwares\Git\cmd;D:\Softwares\AgensGraph\bin;D:\Softwares\GitExtension\;D:\Softwares\apache-maven-3.8.1\bin;C:\Program Files\Java\jdk1.8.0_291\bin;C:\Program Files\Java\jre1.8.0_291\bin;D:\Softwares\Putty\;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.8.0_291\bin;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Apache Software Foundation\Tomcat 9.0\bin;D:\Softwares\apache-maven-3.8.1\bin\bin;C:\Users\admin\AppData\Roaming\npm;.]
27-Aug-2021 22:16:29.895 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
27-Aug-2021 22:16:29.912 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [430] milliseconds
27-Aug-2021 22:16:29.925 WARNING [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = site_scorecard Property maxActive is not used in DBCP2, use maxTotal instead. maxTotal default value is 8. You have set value of "100" for "maxActive" property, which is being ignored.
27-Aug-2021 22:16:29.925 WARNING [main] org.apache.tomcat.dbcp.dbcp2.BasicDataSourceFactory.getObjectInstance Name = site_scorecard Property maxWait is not used in DBCP2 , use maxWaitMillis instead. maxWaitMillis default value is -1. You have set value of "10000" for "maxWait" property, which is being ignored.
27-Aug-2021 22:16:29.945 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
27-Aug-2021 22:16:29.945 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.52]
27-Aug-2021 22:16:29.962 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\scorecard.war]
27-Aug-2021 22:16:32.925 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
22:16:34,932 INFO  [LogHelper:31] HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
22:16:35,089 INFO  [Version:37] HHH000412: Hibernate Core {5.0.7.Final}
22:16:35,092 INFO  [Environment:213] HHH000206: hibernate.properties not found
22:16:35,097 INFO  [Environment:317] HHH000021: Bytecode provider name : javassist
22:16:35,192 INFO  [Version:66] HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
22:16:35,811 INFO  [ENGINE:?] checkpointClose start
22:16:35,812 INFO  [ENGINE:?] checkpointClose synched
22:16:35,825 INFO  [ENGINE:?] dataFileCache open start
22:16:35,906 INFO  [ENGINE:?] dataFileCache open end
22:16:35,941 INFO  [ENGINE:?] checkpointClose script done
22:16:35,942 INFO  [ENGINE:?] dataFileCache commit start
22:16:35,976 INFO  [ENGINE:?] dataFileCache commit end
22:16:36,100 INFO  [ENGINE:?] checkpointClose end
22:16:36,318 INFO  [Dialect:156] HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
22:16:36,888 WARN  [SessionFactoryBuilderImpl:648] Unrecognized hbm2ddl_auto value : none.  Supported values include create, create-drop, update, and validate.  Ignoring
22:16:37,398 INFO  [LogHelper:31] HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
22:16:37,614 WARN  [JdbcEnvironmentInitiator:132] HHH000342: Could not obtain connection to query metadata : Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "scorecarduser")
22:16:37,617 INFO  [Dialect:156] HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
22:16:37,622 INFO  [LobCreatorBuilderImpl:63] HHH000422: Disabling contextual LOB creation as connection was null
22:16:37,624 INFO  [BasicTypeRegistry:138] HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@302e3484
22:16:37,660 WARN  [SessionFactoryBuilderImpl:648] Unrecognized hbm2ddl_auto value : none.  Supported values include create, create-drop, update, and validate.  Ignoring
22:16:37,686 WARN  [EntityManagerFactoryRegistry:63] HHH000436: Entity manager factory name (default) is already registered.  If entity manager will be clustered or passivated, specify a unique value for property 'hibernate.ejb.entitymanager_factory_name'
22:16:37,973 INFO  [QueryTranslatorFactoryInitiator:47] HHH000397: Using ASTQueryTranslatorFactory
22:16:39,104 INFO  [QueryTranslatorFactoryInitiator:47] HHH000397: Using ASTQueryTranslatorFactory
_LOADING VOCABULARY DATABASES FROM THE FOLLOWING RESOURCES:CODES - code_repository/
22:16:39,969 INFO  [VocabularyLoadRunner:81] Loading vocabularies at: code_repository/...
22:16:39,972 ERROR [VocabularyLoadRunner:89] Failed to load configured vocabulary directory.
java.lang.NullPointerException
        at org.sitenv.service.ccda.smartscorecard.loader.VocabularyLoadRunner.loadDirectory(VocabularyLoadRunner.java:28)
        at org.sitenv.service.ccda.smartscorecard.loader.VocabularyLoadRunner.afterPropertiesSet(VocabularyLoadRunner.java:82)_
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4766)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
27-Aug-2021 22:16:40.096 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\scorecard.war] has finished in [10,133] ms
27-Aug-2021 22:16:40.097 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\docs]
27-Aug-2021 22:16:40.123 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\docs] has finished in [26] ms
27-Aug-2021 22:16:40.124 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\manager]
27-Aug-2021 22:16:40.168 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\manager] has finished in [44] ms
27-Aug-2021 22:16:40.169 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\ROOT]
27-Aug-2021 22:16:40.190 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\Program Files\Apache Software Foundation\Tomcat 9.0\webapps\ROOT] has finished in [22] ms
27-Aug-2021 22:16:40.194 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
27-Aug-2021 22:16:40.210 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [10297] milliseconds

**Comment by Savithanpc** [comment]
Hello monika, 
Please help on me the above issue.
